spring:
  kafka:
    bootstrap-servers: kafka:9092
    ingester:
      topic: airline-event
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

logging:
  level:
    org.springframework.kafka: DEBUG
