spring:
  application:
    name: spark-recommender-job
  datasource:
    url: jdbc:postgresql://postgres:5432/airline_app_db
    username: airline_app_user
    password: airline_app_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

spark-recommender:
  minio-properties:
    url: http://minio:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: warehouse
  iceberg-properties:
    catalog-url: jdbc:postgresql://postgres:5432/iceberg
    catalog-user: postgres
    catalog-password: postgres
    warehouse-path: s3a://warehouse/
  table-properties:
    catalog-name: postgres_catalog
    database-name: default
    table-name: airline_event

logging:
  level:
    org.springframework: INFO
    org.apache.spark: WARN
    org.apache.iceberg: INFO
    ir.airline.sparkrecommender: INFO