spring:
  application:
    name: spark-recommender-job

spark-recommender:
  minio-properties:
    url: http://minio:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: airline-data
  iceberg-properties:
    catalog-url: jdbc:postgresql://postgres:5432/iceberg
    catalog-user: postgres
    catalog-password: postgres
    warehouse-path: s3a://airline-data/
  table-properties:
    catalog-name: postgres_catalog
    database-name: default
    table-name: airline_event
  postgres-properties:
    url: jdbc:postgresql://postgres:5432/airline
    user: postgres
    password: postgres

logging:
  level:
    org.springframework: INFO
    org.apache.spark: WARN
    org.apache.iceberg: INFO
    ir.airline.sparkrecommender: INFO