spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      topic: airline-event
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://schema-registry:8081
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
logging:
  level:
    org.springframework.kafka: DEBUG
